ALTER TABLE trip_flights
  ADD COLUMN IF NOT EXISTS flight_number TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS stop_details JSONB NOT NULL DEFAULT '[]'::jsonb;
